# Generated by Django 3.2.16 on 2022-11-22 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('issuetype', models.CharField(choices=[('BUG', 'Bug'), ('TASK', 'Task'), ('STORY', 'Story'), ('EPIC', 'Epic')], default='BUG', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('IN REVIEW', 'In Review'), ('CODE COMPLETE', 'Code Complete'), ('DONE', 'Done')], default='OPEN', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraapp1.project')),
            ],
        ),
    ]
