# Generated by Django 3.2.16 on 2022-11-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraapp1', '0002_auto_20221122_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='project',
            new_name='project_id',
        ),
    ]
