# Generated by Django 3.2.16 on 2022-11-28 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jiraapp1', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraapp1.issues')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraapp1.project')),
            ],
        ),
    ]
